services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: talabat-api

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      PORT: 3000
      DB_URL: mongodb://mongo:27017/talabat
      REDIS_URL: redis://redis:6379

    depends_on:
      mongo:
        condition: service_healthy

      redis:
        condition: service_healthy

    restart: unless-stopped

  mongo:
    image: mongo:8.0

    container_name: talabat-mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  redis:
    image: redis:7-alpine

    container_name: talabat-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  mongo_data:
  redis_data: